// Component-specific tokens verified against the public library styles.
export const tabsTokens = [
  { token: '--tabs-content-gap', description: 'Space between the tab list and its panel.' },
  { token: '--tabs-border-width', description: 'Tab-list divider thickness.' },
  { token: '--tabs-border', description: 'Tab-list divider colour.' },
  { token: '--tabs-content', description: 'Panel text colour.' },
  { token: '--tabs-focus-ring-width', description: 'Keyboard-focus outline thickness.' },
  { token: '--tabs-focus-ring-offset', description: 'Keyboard-focus outline position.' },
  { token: '--tab-min-height', description: 'Minimum tab target height.' },
  { token: '--tab-padding-block', description: 'Vertical tab padding.' },
  { token: '--tab-padding-inline', description: 'Horizontal tab padding.' },
  { token: '--tab-content', description: 'Default tab text colour.' },
  { token: '--tab-content-selected', description: 'Selected tab text colour.' },
  { token: '--tab-background-hovered', description: 'Tab background while hovered.' },
  { token: '--tab-background-pressed', description: 'Tab background while pressed.' },
  { token: '--tab-indicator', description: 'Selection indicator colour.' },
  { token: '--tab-indicator-width', description: 'Selection indicator thickness.' },
  { token: '--tab-motion-duration', description: 'Selection indicator movement duration; motion stops with reduced motion.' },
  { token: '--tab-panel-padding', description: 'Padding inside the content panel.' },
  { token: '--tab-panel-preferred-width', description: 'Preferred panel width before a vertical layout wraps the panel below the list.' },
]

export const dialogTokens = [
  { token: '--modal-z-index', description: 'Overlay stacking level.' },
  { token: '--modal-viewport-padding', description: 'Minimum space between the modal and viewport edges.' },
  { token: '--modal-max-width', description: 'Maximum modal width.' },
  { token: '--modal-border-width', description: 'Modal border thickness.' },
  { token: '--modal-border-radius', description: 'Modal corner radius.' },
  { token: '--modal-backdrop', description: 'Backdrop behind the modal.' },
  { token: '--modal-background', description: 'Modal surface colour.' },
  { token: '--modal-content', description: 'Modal text colour.' },
  { token: '--modal-border', description: 'Modal border colour.' },
  { token: '--modal-motion-duration', description: 'Entry and exit duration; motion stops with reduced motion.' },
  { token: '--modal-enter-scale', description: 'Modal scale at the start of entry and end of exit.' },
  { token: '--dialog-padding', description: 'Padding inside the dialog.' },
  { token: '--dialog-content-gap', description: 'Space after the title and paragraphs, and before the actions.' },
  { token: '--dialog-actions-gap', description: 'Space between action buttons.' },
  { token: '--dialog-focus-ring-width', description: 'Dialog keyboard-focus outline thickness.' },
]
