import type { ReactNode } from 'react'
import {
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  AudioBarsIcon,
  BriefcaseIcon,
  BulbIcon,
  CaptionsIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  CopyIcon,
  DancePadIcon,
  DownloadIcon,
  DrumIcon,
  EmailIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  ExitIcon,
  FallingIcon,
  FigureIcon,
  LinkedInIcon,
  LoadingIcon,
  LocationIcon,
  MenuIcon,
  MicIcon,
  MicOffIcon,
  MinusIcon,
  MoreIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  PanelRightCloseIcon,
  PanelRightOpenIcon,
  PauseIcon,
  PlayIcon,
  PlusIcon,
  PulseIcon,
  RedoIcon,
  ResetIcon,
  RewindToStartIcon,
  RisingIcon,
  SparkleIcon,
  TrashIcon,
  TrustIcon,
  UndoIcon,
  VideoCameraIcon,
  VolumeHighIcon,
  VolumeLowIcon,
  VolumeMutedIcon,
  VolumeOffIcon,
  WaveformIcon,
  WavesIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from '@decocode/mezzanine'

export interface IconDefinition {
  componentName: string
  icon: ReactNode
  name: string
}

export const iconDefinitions: IconDefinition[] = [
  { name: 'Arrow down', componentName: 'ArrowDownIcon', icon: <ArrowDownIcon /> },
  { name: 'Arrow left', componentName: 'ArrowLeftIcon', icon: <ArrowLeftIcon /> },
  { name: 'Arrow right', componentName: 'ArrowRightIcon', icon: <ArrowRightIcon /> },
  { name: 'Arrow up', componentName: 'ArrowUpIcon', icon: <ArrowUpIcon /> },
  { name: 'Audio bars', componentName: 'AudioBarsIcon', icon: <AudioBarsIcon /> },
  { name: 'Briefcase', componentName: 'BriefcaseIcon', icon: <BriefcaseIcon /> },
  { name: 'Bulb', componentName: 'BulbIcon', icon: <BulbIcon /> },
  { name: 'Captions', componentName: 'CaptionsIcon', icon: <CaptionsIcon /> },
  { name: 'Check', componentName: 'CheckIcon', icon: <CheckIcon /> },
  { name: 'Chevron down', componentName: 'ChevronDownIcon', icon: <ChevronDownIcon /> },
  { name: 'Chevron left', componentName: 'ChevronLeftIcon', icon: <ChevronLeftIcon /> },
  { name: 'Chevron right', componentName: 'ChevronRightIcon', icon: <ChevronRightIcon /> },
  { name: 'Chevron up', componentName: 'ChevronUpIcon', icon: <ChevronUpIcon /> },
  { name: 'Close', componentName: 'CloseIcon', icon: <CloseIcon /> },
  { name: 'Copy', componentName: 'CopyIcon', icon: <CopyIcon /> },
  { name: 'Dance pad', componentName: 'DancePadIcon', icon: <DancePadIcon /> },
  { name: 'Download', componentName: 'DownloadIcon', icon: <DownloadIcon /> },
  { name: 'Drum', componentName: 'DrumIcon', icon: <DrumIcon /> },
  { name: 'Email', componentName: 'EmailIcon', icon: <EmailIcon /> },
  { name: 'External link', componentName: 'ExternalLinkIcon', icon: <ExternalLinkIcon /> },
  { name: 'Eye', componentName: 'EyeIcon', icon: <EyeIcon /> },
  { name: 'Eye off', componentName: 'EyeOffIcon', icon: <EyeOffIcon /> },
  { name: 'Exit', componentName: 'ExitIcon', icon: <ExitIcon /> },
  { name: 'Falling', componentName: 'FallingIcon', icon: <FallingIcon /> },
  { name: 'Figure', componentName: 'FigureIcon', icon: <FigureIcon /> },
  { name: 'LinkedIn', componentName: 'LinkedInIcon', icon: <LinkedInIcon /> },
  { name: 'Loading', componentName: 'LoadingIcon', icon: <LoadingIcon className="icon-loading" /> },
  { name: 'Location', componentName: 'LocationIcon', icon: <LocationIcon /> },
  { name: 'Menu', componentName: 'MenuIcon', icon: <MenuIcon /> },
  { name: 'Microphone', componentName: 'MicIcon', icon: <MicIcon /> },
  { name: 'Microphone off', componentName: 'MicOffIcon', icon: <MicOffIcon /> },
  { name: 'Minus', componentName: 'MinusIcon', icon: <MinusIcon /> },
  { name: 'More', componentName: 'MoreIcon', icon: <MoreIcon /> },
  { name: 'Music note', componentName: 'MusicNoteIcon', icon: <MusicNoteIcon /> },
  { name: 'Music notes', componentName: 'MusicNotesIcon', icon: <MusicNotesIcon /> },
  { name: 'Panel right close', componentName: 'PanelRightCloseIcon', icon: <PanelRightCloseIcon /> },
  { name: 'Panel right open', componentName: 'PanelRightOpenIcon', icon: <PanelRightOpenIcon /> },
  { name: 'Pause', componentName: 'PauseIcon', icon: <PauseIcon /> },
  { name: 'Play', componentName: 'PlayIcon', icon: <PlayIcon /> },
  { name: 'Plus', componentName: 'PlusIcon', icon: <PlusIcon /> },
  { name: 'Pulse', componentName: 'PulseIcon', icon: <PulseIcon /> },
  { name: 'Redo', componentName: 'RedoIcon', icon: <RedoIcon /> },
  { name: 'Reset', componentName: 'ResetIcon', icon: <ResetIcon /> },
  { name: 'Rewind to start', componentName: 'RewindToStartIcon', icon: <RewindToStartIcon /> },
  { name: 'Rising', componentName: 'RisingIcon', icon: <RisingIcon /> },
  { name: 'Sparkle', componentName: 'SparkleIcon', icon: <SparkleIcon /> },
  { name: 'Trash', componentName: 'TrashIcon', icon: <TrashIcon /> },
  { name: 'Trust', componentName: 'TrustIcon', icon: <TrustIcon /> },
  { name: 'Undo', componentName: 'UndoIcon', icon: <UndoIcon /> },
  { name: 'Video camera', componentName: 'VideoCameraIcon', icon: <VideoCameraIcon /> },
  { name: 'Volume high', componentName: 'VolumeHighIcon', icon: <VolumeHighIcon /> },
  { name: 'Volume low', componentName: 'VolumeLowIcon', icon: <VolumeLowIcon /> },
  { name: 'Volume muted', componentName: 'VolumeMutedIcon', icon: <VolumeMutedIcon /> },
  { name: 'Volume off', componentName: 'VolumeOffIcon', icon: <VolumeOffIcon /> },
  { name: 'Waveform', componentName: 'WaveformIcon', icon: <WaveformIcon /> },
  { name: 'Waves', componentName: 'WavesIcon', icon: <WavesIcon /> },
  { name: 'Zoom in', componentName: 'ZoomInIcon', icon: <ZoomInIcon /> },
  { name: 'Zoom out', componentName: 'ZoomOutIcon', icon: <ZoomOutIcon /> },
]
